apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: k8smissions
spec:
  limits:
  - type: Container
    max:
      cpu: '1'
      memory: 512Mi
    default:
      cpu: 200m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 64Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: noisy-pod
  namespace: k8smissions
spec:
  containers:
  - name: noisy
    image: busybox:1.36
    command:
    - /bin/sh
    - -c
    - while true; do :; done
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
