apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
  namespace: k8smissions
  labels:
    app: oom-pod
spec:
  containers:
  - name: oom-pod
    image: python:3.11-alpine
    command:
    - python
    - -c
    - data=['x'*1024*1024 for _ in range(128)]; import time; time.sleep(3600)
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 64Mi
