apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-app
  namespace: k8smissions
  labels:
    app: helm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-app
  template:
    metadata:
      labels:
        app: helm-app
    spec:
      containers:
      - name: helm-app
        image: nginx:latest
        ports:
        - containerPort: 80
