apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutator
webhooks:
- name: mutate.example.com
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: mutator-svc
      namespace: operators
      port: 443
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Fail
  sideEffects: None
