apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns
  namespace: kube-system
data:
  Corefile: "cluster.local:53 {\n    errors\n    cache 30\n    reload\n    loop\n\
    \    bind 169.254.20.10\n    forward . __PILLAR__CLUSTER__DNS__\n    prometheus\
    \ :9253\n}\n"
  enabled: 'false'
