apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaky-app
  namespace: k8smissions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaky
  template:
    metadata:
      labels:
        app: leaky
    spec:
      containers:
      - name: app
        image: leaky-app:v1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
