apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog
  namespace: k8smissions
  labels:
    app: cpu-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog
  template:
    metadata:
      labels:
        app: cpu-hog
    spec:
      containers:
      - name: cpu-hog
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - while true; do :; done
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
