apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilient-app
  namespace: k8smissions
spec:
  replicas: 5
  selector:
    matchLabels:
      app: resilient
  template:
    metadata:
      labels:
        app: resilient
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: resilient
      containers:
      - name: app
        image: nginx:1.25
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
